// Code generated by entc, DO NOT EDIT.

package alias

const (
	// Label holds the string label denoting the alias type in the database.
	Label = "alias"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldShort holds the string denoting the short field in the database.
	FieldShort = "short"
	// FieldLong holds the string denoting the long field in the database.
	FieldLong = "long"
	// Table holds the table name of the alias in the database.
	Table = "alias"
)

// Columns holds all SQL columns for alias fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldShort,
	FieldLong,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
