// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ras0q/traq-kinano-cli/ent/alias"
	"github.com/gofrs/uuid"
)

// AliasCreate is the builder for creating a Alias entity.
type AliasCreate struct {
	config
	mutation *AliasMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (ac *AliasCreate) SetUserID(u uuid.UUID) *AliasCreate {
	ac.mutation.SetUserID(u)
	return ac
}

// SetShort sets the "short" field.
func (ac *AliasCreate) SetShort(s string) *AliasCreate {
	ac.mutation.SetShort(s)
	return ac
}

// SetLong sets the "long" field.
func (ac *AliasCreate) SetLong(s string) *AliasCreate {
	ac.mutation.SetLong(s)
	return ac
}

// SetID sets the "id" field.
func (ac *AliasCreate) SetID(u uuid.UUID) *AliasCreate {
	ac.mutation.SetID(u)
	return ac
}

// Mutation returns the AliasMutation object of the builder.
func (ac *AliasCreate) Mutation() *AliasMutation {
	return ac.mutation
}

// Save creates the Alias in the database.
func (ac *AliasCreate) Save(ctx context.Context) (*Alias, error) {
	var (
		err  error
		node *Alias
	)
	if len(ac.hooks) == 0 {
		if err = ac.check(); err != nil {
			return nil, err
		}
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AliasMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ac.check(); err != nil {
				return nil, err
			}
			ac.mutation = mutation
			if node, err = ac.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			if ac.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AliasCreate) SaveX(ctx context.Context) *Alias {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AliasCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AliasCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AliasCreate) check() error {
	if _, ok := ac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "user_id"`)}
	}
	if _, ok := ac.mutation.Short(); !ok {
		return &ValidationError{Name: "short", err: errors.New(`ent: missing required field "short"`)}
	}
	if _, ok := ac.mutation.Long(); !ok {
		return &ValidationError{Name: "long", err: errors.New(`ent: missing required field "long"`)}
	}
	return nil
}

func (ac *AliasCreate) sqlSave(ctx context.Context) (*Alias, error) {
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(uuid.UUID)
	}
	return _node, nil
}

func (ac *AliasCreate) createSpec() (*Alias, *sqlgraph.CreateSpec) {
	var (
		_node = &Alias{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: alias.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: alias.FieldID,
			},
		}
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.UserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: alias.FieldUserID,
		})
		_node.UserID = value
	}
	if value, ok := ac.mutation.Short(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: alias.FieldShort,
		})
		_node.Short = value
	}
	if value, ok := ac.mutation.Long(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: alias.FieldLong,
		})
		_node.Long = value
	}
	return _node, _spec
}

// AliasCreateBulk is the builder for creating many Alias entities in bulk.
type AliasCreateBulk struct {
	config
	builders []*AliasCreate
}

// Save creates the Alias entities in the database.
func (acb *AliasCreateBulk) Save(ctx context.Context) ([]*Alias, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Alias, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AliasMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AliasCreateBulk) SaveX(ctx context.Context) []*Alias {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AliasCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AliasCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
